version: '3'
services:
  coding-textbook-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      DOMAIN_NAME: "https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}/"
    ports:
      - "3050:3050"
    container_name: coding-textbook-server
    volumes:
       - ./server:/usr/src/coding-textbook/server
  coding-textbook-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    container_name: coding-textbook-client
    stdin_open: true
    volumes:
       - ./client:/usr/src/coding-textbook/client
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: